# ScummVM's source list, as ScummVM's own module.mk files give it
# for the feature switches in mk/scummvm-features.mk.
#
# GENERATED — do not edit. Produced by mk/harvest-sources.mk, which
# reads upstream's makefiles; run 'make regen-sources' to write it
# again after the scummvm submodule pin moves or a feature switch
# changes. Nothing else changes the answer, and the build never
# reads upstream's makefiles itself.
#
# Paths are relative to the scummvm submodule.
SVM_SRCS := \
	base/test_new_standards.cpp \
	base/main.cpp \
	base/commandLine.cpp \
	base/plugins.cpp \
	base/version.cpp \
	engines/achievements.cpp \
	engines/advancedDetector.cpp \
	engines/dialogs.cpp \
	engines/engine.cpp \
	engines/game.cpp \
	engines/metaengine.cpp \
	engines/obsolete.cpp \
	engines/savestate.cpp \
	engines/scumm/actor.cpp \
	engines/scumm/akos.cpp \
	engines/scumm/base-costume.cpp \
	engines/scumm/base-costume-optimised.cpp \
	engines/scumm/bomp.cpp \
	engines/scumm/boxes.cpp \
	engines/scumm/camera.cpp \
	engines/scumm/cdda.cpp \
	engines/scumm/charset.cpp \
	engines/scumm/charset-fontdata.cpp \
	engines/scumm/costume.cpp \
	engines/scumm/cursor.cpp \
	engines/scumm/debugger.cpp \
	engines/scumm/dialogs.cpp \
	engines/scumm/file.cpp \
	engines/scumm/file_engine.cpp \
	engines/scumm/file_nes.cpp \
	engines/scumm/gfx_gui.cpp \
	engines/scumm/gfx_mac.cpp \
	engines/scumm/gfx_nes.cpp \
	engines/scumm/gfx_towns.cpp \
	engines/scumm/gfx.cpp \
	engines/scumm/he/mixer_he.cpp \
	engines/scumm/he/resource_he.cpp \
	engines/scumm/he/script_v60he.cpp \
	engines/scumm/he/script_v70he.cpp \
	engines/scumm/he/sound_he.cpp \
	engines/scumm/help.cpp \
	engines/scumm/imuse/imuse.cpp \
	engines/scumm/imuse/imuse_part.cpp \
	engines/scumm/imuse/imuse_player.cpp \
	engines/scumm/imuse/instrument.cpp \
	engines/scumm/imuse/sysex_samnmax.cpp \
	engines/scumm/imuse/sysex_scumm.cpp \
	engines/scumm/imuse/drivers/amiga.cpp \
	engines/scumm/imuse/drivers/fmtowns.cpp \
	engines/scumm/imuse/drivers/midi.cpp \
	engines/scumm/imuse/drivers/macintosh.cpp \
	engines/scumm/imuse/drivers/pcspk.cpp \
	engines/scumm/input.cpp \
	engines/scumm/ks_check.cpp \
	engines/scumm/macgui/macgui.cpp \
	engines/scumm/macgui/macgui_dialogwindow.cpp \
	engines/scumm/macgui/macgui_impl.cpp \
	engines/scumm/macgui/macgui_indy3.cpp \
	engines/scumm/macgui/macgui_loom.cpp \
	engines/scumm/macgui/macgui_strings.cpp \
	engines/scumm/macgui/macgui_v5.cpp \
	engines/scumm/macgui/macgui_v6.cpp \
	engines/scumm/macgui/macgui_widgets.cpp \
	engines/scumm/metaengine.cpp \
	engines/scumm/midiparser_ro.cpp \
	engines/scumm/object.cpp \
	engines/scumm/palette.cpp \
	engines/scumm/playback.cpp \
	engines/scumm/players/player_ad.cpp \
	engines/scumm/players/player_apple2.cpp \
	engines/scumm/players/player_he.cpp \
	engines/scumm/players/player_mac_indy3.cpp \
	engines/scumm/players/player_mac_loom_monkey.cpp \
	engines/scumm/players/player_mac_new.cpp \
	engines/scumm/players/player_mod.cpp \
	engines/scumm/players/player_nes.cpp \
	engines/scumm/players/player_pce.cpp \
	engines/scumm/players/player_sid.cpp \
	engines/scumm/players/player_towns.cpp \
	engines/scumm/players/player_v1.cpp \
	engines/scumm/players/player_v2.cpp \
	engines/scumm/players/player_v2a.cpp \
	engines/scumm/players/player_v2base.cpp \
	engines/scumm/players/player_v2cms.cpp \
	engines/scumm/players/player_v3a.cpp \
	engines/scumm/players/player_v4a.cpp \
	engines/scumm/resource_v2.cpp \
	engines/scumm/resource_v3.cpp \
	engines/scumm/resource_v4.cpp \
	engines/scumm/resource.cpp \
	engines/scumm/room.cpp \
	engines/scumm/saveload.cpp \
	engines/scumm/script_v0.cpp \
	engines/scumm/script_v2.cpp \
	engines/scumm/script_v3.cpp \
	engines/scumm/script_v4.cpp \
	engines/scumm/script_v5.cpp \
	engines/scumm/script_v6.cpp \
	engines/scumm/script.cpp \
	engines/scumm/scumm.cpp \
	engines/scumm/sound.cpp \
	engines/scumm/soundcd.cpp \
	engines/scumm/soundse.cpp \
	engines/scumm/string.cpp \
	engines/scumm/usage_bits.cpp \
	engines/scumm/util.cpp \
	engines/scumm/vars.cpp \
	engines/scumm/verbs.cpp \
	engines/scumm/nut_renderer.cpp \
	engines/scumm/string_v7.cpp \
	engines/scumm/script_v8.cpp \
	engines/scumm/imuse_digi/dimuse_bndmgr.cpp \
	engines/scumm/imuse_digi/dimuse_codecs.cpp \
	engines/scumm/imuse_digi/dimuse_sndmgr.cpp \
	engines/scumm/imuse_digi/dimuse_tables.cpp \
	engines/scumm/imuse_digi/dimuse_engine.cpp \
	engines/scumm/imuse_digi/dimuse_cmds.cpp \
	engines/scumm/imuse_digi/dimuse_dispatch.cpp \
	engines/scumm/imuse_digi/dimuse_fades.cpp \
	engines/scumm/imuse_digi/dimuse_files.cpp \
	engines/scumm/imuse_digi/dimuse_groups.cpp \
	engines/scumm/imuse_digi/dimuse_internalmixer.cpp \
	engines/scumm/imuse_digi/dimuse_scripts.cpp \
	engines/scumm/imuse_digi/dimuse_streamer.cpp \
	engines/scumm/imuse_digi/dimuse_tracks.cpp \
	engines/scumm/imuse_digi/dimuse_triggers.cpp \
	engines/scumm/imuse_digi/dimuse_utils.cpp \
	engines/scumm/imuse_digi/dimuse_wave.cpp \
	engines/scumm/imuse_digi/dimuse_waveout.cpp \
	engines/scumm/insane/insane.cpp \
	engines/scumm/insane/insane_ben.cpp \
	engines/scumm/insane/insane_enemy.cpp \
	engines/scumm/insane/insane_scenes.cpp \
	engines/scumm/insane/insane_iact.cpp \
	engines/scumm/insane/rebel/rebel_audio.cpp \
	engines/scumm/insane/rebel/rebel_gamepad.cpp \
	engines/scumm/insane/rebel1/rebel.cpp \
	engines/scumm/insane/rebel1/audio.cpp \
	engines/scumm/insane/rebel1/iact.cpp \
	engines/scumm/insane/rebel1/levels.cpp \
	engines/scumm/insane/rebel1/menu.cpp \
	engines/scumm/insane/rebel1/render.cpp \
	engines/scumm/insane/rebel1/runlevels.cpp \
	engines/scumm/insane/rebel1/saveload.cpp \
	engines/scumm/insane/rebel2/rebel.cpp \
	engines/scumm/insane/rebel2/audio.cpp \
	engines/scumm/insane/rebel2/iact.cpp \
	engines/scumm/insane/rebel2/levels.cpp \
	engines/scumm/insane/rebel2/menu.cpp \
	engines/scumm/insane/rebel2/render.cpp \
	engines/scumm/insane/rebel2/runlevels.cpp \
	engines/scumm/smush/codec1.cpp \
	engines/scumm/smush/codec20.cpp \
	engines/scumm/smush/codec37.cpp \
	engines/scumm/smush/codec47.cpp \
	engines/scumm/smush/smush_player.cpp \
	engines/scumm/smush/rebel/codec_ra1.cpp \
	engines/scumm/smush/rebel/codec_ra2.cpp \
	engines/scumm/smush/rebel/font_rebel2.cpp \
	engines/scumm/smush/rebel/smush_multi_font.cpp \
	engines/scumm/smush/rebel/smush_player_rebel.cpp \
	engines/scumm/smush/rebel/smush_player_ra1.cpp \
	engines/scumm/smush/rebel/smush_player_ra2.cpp \
	gui/about.cpp \
	gui/browser.cpp \
	gui/chooser.cpp \
	gui/console.cpp \
	gui/debugger.cpp \
	gui/dialog.cpp \
	gui/dump-all-dialogs.cpp \
	gui/editgamedialog.cpp \
	gui/error.cpp \
	gui/EventRecorder.cpp \
	gui/filebrowser-dialog.cpp \
	gui/gui-manager.cpp \
	gui/helpdialog.cpp \
	gui/imagealbum-dialog.cpp \
	gui/launcher.cpp \
	gui/massadd.cpp \
	gui/message.cpp \
	gui/MetadataParser.cpp \
	gui/object.cpp \
	gui/options.cpp \
	gui/predictivedialog.cpp \
	gui/printing-dialog.cpp \
	gui/saveload.cpp \
	gui/saveload-dialog.cpp \
	gui/shaderbrowser-dialog.cpp \
	gui/textviewer.cpp \
	gui/themebrowser.cpp \
	gui/ThemeEngine.cpp \
	gui/ThemeEval.cpp \
	gui/ThemeLayout.cpp \
	gui/ThemeParser.cpp \
	gui/Tooltip.cpp \
	gui/unknown-game-dialog.cpp \
	gui/widget.cpp \
	gui/animation/Animation.cpp \
	gui/animation/FluidScroll.cpp \
	gui/animation/RepeatAnimationWrapper.cpp \
	gui/animation/SequenceAnimationComposite.cpp \
	gui/widgets/editable.cpp \
	gui/widgets/edittext.cpp \
	gui/widgets/grid.cpp \
	gui/widgets/groupedlist.cpp \
	gui/widgets/list.cpp \
	gui/widgets/popup.cpp \
	gui/widgets/richtext.cpp \
	gui/widgets/scrollbar.cpp \
	gui/widgets/scrollcontainer.cpp \
	gui/widgets/tab.cpp \
	backends/base-backend.cpp \
	backends/modular-backend.cpp \
	backends/audiocd/audiocd-stream.cpp \
	backends/audiocd/default/default-audiocd.cpp \
	backends/events/default/default-events.cpp \
	backends/fs/abstract-fs.cpp \
	backends/fs/stdiostream.cpp \
	backends/keymapper/action.cpp \
	backends/keymapper/hardware-input.cpp \
	backends/keymapper/input-watcher.cpp \
	backends/keymapper/keymap.cpp \
	backends/keymapper/keymapper.cpp \
	backends/keymapper/remap-widget.cpp \
	backends/keymapper/standard-actions.cpp \
	backends/keymapper/virtual-mouse.cpp \
	backends/log/log.cpp \
	backends/midi/alsa.cpp \
	backends/midi/dmedia.cpp \
	backends/midi/seq.cpp \
	backends/midi/sndio.cpp \
	backends/midi/stmidi.cpp \
	backends/midi/timidity.cpp \
	backends/saves/savefile.cpp \
	backends/saves/default/default-saves.cpp \
	backends/timer/default/default-timer.cpp \
	backends/events/sdl/sdl-common-events.cpp \
	backends/graphics/sdl/sdl-graphics.cpp \
	backends/graphics/surfacesdl/surfacesdl-graphics.cpp \
	backends/mixer/sdl/sdl-mixer.cpp \
	backends/mixer/null/null-mixer.cpp \
	backends/mutex/sdl/sdl-mutex.cpp \
	backends/timer/sdl/sdl-timer.cpp \
	backends/events/sdl/sdl2-events.cpp \
	backends/plugins/sdl/sdl-provider.cpp \
	video/3do_decoder.cpp \
	video/4xm_decoder.cpp \
	video/4xm_utils.cpp \
	video/avi_decoder.cpp \
	video/coktel_decoder.cpp \
	video/dxa_decoder.cpp \
	video/flic_decoder.cpp \
	video/mpegps_decoder.cpp \
	video/mve_decoder.cpp \
	video/paco_decoder.cpp \
	video/psx_decoder.cpp \
	video/qt_decoder.cpp \
	video/qtvr_decoder.cpp \
	video/smk_decoder.cpp \
	video/subtitles.cpp \
	video/video_decoder.cpp \
	image/ani.cpp \
	image/bmp.cpp \
	image/cel_3do.cpp \
	image/cicn.cpp \
	image/icocur.cpp \
	image/iff.cpp \
	image/jpeg.cpp \
	image/neo.cpp \
	image/pcx.cpp \
	image/pict.cpp \
	image/png.cpp \
	image/scr.cpp \
	image/tga.cpp \
	image/xbm.cpp \
	image/codecs/bmp_raw.cpp \
	image/codecs/cinepak.cpp \
	image/codecs/codec.cpp \
	image/codecs/dither.cpp \
	image/codecs/hlz.cpp \
	image/codecs/msrle.cpp \
	image/codecs/msrle4.cpp \
	image/codecs/msvideo1.cpp \
	image/codecs/qtrle.cpp \
	image/codecs/rpza.cpp \
	image/codecs/smc.cpp \
	graphics/big5.cpp \
	graphics/blit/blit.cpp \
	graphics/blit/blit-alpha.cpp \
	graphics/blit/blit-fast.cpp \
	graphics/blit/blit-generic.cpp \
	graphics/blit/blit-scale.cpp \
	graphics/color_quantizer.cpp \
	graphics/cursorman.cpp \
	graphics/dirtyrects.cpp \
	graphics/font.cpp \
	graphics/fontman.cpp \
	graphics/fonts/amigafont.cpp \
	graphics/fonts/bdf.cpp \
	graphics/fonts/bgifont.cpp \
	graphics/fonts/consolefont.cpp \
	graphics/fonts/dosfont.cpp \
	graphics/fonts/freetype.cpp \
	graphics/fonts/macfont.cpp \
	graphics/fonts/newfont_big.cpp \
	graphics/fonts/newfont.cpp \
	graphics/fonts/ttf.cpp \
	graphics/fonts/winfont.cpp \
	graphics/framelimiter.cpp \
	graphics/image-archive.cpp \
	graphics/korfont.cpp \
	graphics/larryScale.cpp \
	graphics/maccursor.cpp \
	graphics/macgui/datafiles.cpp \
	graphics/macgui/macbutton.cpp \
	graphics/macgui/macdialog.cpp \
	graphics/macgui/macfontmanager.cpp \
	graphics/macgui/macmenu.cpp \
	graphics/macgui/macpopupmenu.cpp \
	graphics/macgui/mactext.cpp \
	graphics/macgui/mactext-canvas.cpp \
	graphics/macgui/mactext-md.cpp \
	graphics/macgui/mactextwindow.cpp \
	graphics/macgui/macwidget.cpp \
	graphics/macgui/macwindow.cpp \
	graphics/macgui/macwindowborder.cpp \
	graphics/macgui/macwindowmanager.cpp \
	graphics/managed_surface.cpp \
	graphics/nine_patch.cpp \
	graphics/opengl/context.cpp \
	graphics/opengl/debug.cpp \
	graphics/opengl/shader.cpp \
	graphics/opengl/texture.cpp \
	graphics/palette.cpp \
	graphics/pixelformat.cpp \
	graphics/pm5544.cpp \
	graphics/primitives.cpp \
	graphics/riscoscursor.cpp \
	graphics/renderer.cpp \
	graphics/scalerplugin.cpp \
	graphics/scaler/downscaler.cpp \
	graphics/scaler/thumbnail_intern.cpp \
	graphics/screen.cpp \
	graphics/scaler/normal.cpp \
	graphics/sjis.cpp \
	graphics/surface.cpp \
	graphics/svg.cpp \
	graphics/transform_struct.cpp \
	graphics/transform_tools.cpp \
	graphics/thumbnail.cpp \
	graphics/VectorRenderer.cpp \
	graphics/VectorRendererSpec.cpp \
	graphics/wincursor.cpp \
	graphics/yuv_to_rgb.cpp \
	graphics/scaler/aspect.cpp \
	graphics/scaler/dotmatrix.cpp \
	graphics/scaler/sai.cpp \
	graphics/scaler/pm.cpp \
	graphics/scaler/scale2x.cpp \
	graphics/scaler/scale3x.cpp \
	graphics/scaler/scalebit.cpp \
	graphics/scaler/tv.cpp \
	audio/adlib.cpp \
	audio/adlib_ctmidi.cpp \
	audio/adlib_hmisos.cpp \
	audio/adlib_ms.cpp \
	audio/audiostream.cpp \
	audio/casio.cpp \
	audio/chip.cpp \
	audio/cms.cpp \
	audio/fmopl.cpp \
	audio/mac_plugin.cpp \
	audio/mididrv.cpp \
	audio/mididrv_ms.cpp \
	audio/midiparser_hmp.cpp \
	audio/midiparser_qt.cpp \
	audio/midiparser_smf.cpp \
	audio/midiparser_xmidi.cpp \
	audio/midiparser.cpp \
	audio/midiplayer.cpp \
	audio/miles_adlib.cpp \
	audio/miles_midi.cpp \
	audio/mixer.cpp \
	audio/mpu401.cpp \
	audio/mt32gm.cpp \
	audio/musicplugin.cpp \
	audio/null.cpp \
	audio/rate.cpp \
	audio/sid.cpp \
	audio/ym2149.cpp \
	audio/timestamp.cpp \
	audio/decoders/3do.cpp \
	audio/decoders/aac.cpp \
	audio/decoders/adpcm.cpp \
	audio/decoders/aiff.cpp \
	audio/decoders/apc.cpp \
	audio/decoders/asf.cpp \
	audio/decoders/flac.cpp \
	audio/decoders/g711.cpp \
	audio/decoders/iff_sound.cpp \
	audio/decoders/mac_snd.cpp \
	audio/decoders/mp3.cpp \
	audio/decoders/qdm2.cpp \
	audio/decoders/quicktime.cpp \
	audio/decoders/raw.cpp \
	audio/decoders/voc.cpp \
	audio/decoders/vorbis.cpp \
	audio/decoders/wave.cpp \
	audio/decoders/wma.cpp \
	audio/decoders/xa.cpp \
	audio/decoders/xan_dpcm.cpp \
	audio/mods/universaltracker.cpp \
	audio/mods/infogrames.cpp \
	audio/mods/maxtrax.cpp \
	audio/mods/mod_xm_s3m.cpp \
	audio/mods/module.cpp \
	audio/mods/module_mod_xm_s3m.cpp \
	audio/mods/protracker.cpp \
	audio/mods/paula.cpp \
	audio/mods/rjp1.cpp \
	audio/mods/soundfx.cpp \
	audio/mods/tfmx.cpp \
	audio/mods/desktoptracker.cpp \
	audio/softsynth/cms.cpp \
	audio/softsynth/opl/dbopl.cpp \
	audio/softsynth/opl/dosbox.cpp \
	audio/softsynth/opl/mame.cpp \
	audio/softsynth/appleiigs.cpp \
	audio/softsynth/fluidsynth.cpp \
	audio/softsynth/eas.cpp \
	audio/softsynth/pcspk.cpp \
	audio/softsynth/ay8912.cpp \
	audio/softsynth/opl/nuked.cpp \
	audio/softsynth/ym2149.cpp \
	audio/softsynth/fmtowns_pc98/pc98_audio.cpp \
	audio/softsynth/fmtowns_pc98/pcm_common.cpp \
	audio/softsynth/fmtowns_pc98/sega_audio.cpp \
	audio/softsynth/fmtowns_pc98/towns_audio.cpp \
	audio/softsynth/fmtowns_pc98/towns_euphony.cpp \
	audio/softsynth/fmtowns_pc98/towns_pc98_driver.cpp \
	audio/softsynth/fmtowns_pc98/towns_pc98_fmsynth.cpp \
	audio/softsynth/fmtowns_pc98/towns_pc98_plugins.cpp \
	audio/softsynth/sid.cpp \
	audio/softsynth/wave6581.cpp \
	math/aabb.cpp \
	math/angle.cpp \
	math/cosinetables.cpp \
	math/dct.cpp \
	math/fft.cpp \
	math/frustum.cpp \
	math/glmath.cpp \
	math/line2d.cpp \
	math/line3d.cpp \
	math/matrix3.cpp \
	math/matrix4.cpp \
	math/mdct.cpp \
	math/plane.cpp \
	math/quat.cpp \
	math/ray.cpp \
	math/rdft.cpp \
	math/rect2d.cpp \
	math/sinetables.cpp \
	math/sinewindows.cpp \
	math/vector2d.cpp \
	math/vector3d.cpp \
	math/vector4d.cpp \
	common/archive.cpp \
	common/base64.cpp \
	common/btea.cpp \
	common/concatstream.cpp \
	common/config-manager.cpp \
	common/coroutines.cpp \
	common/dbcs-str.cpp \
	common/debug.cpp \
	common/engine_data.cpp \
	common/error.cpp \
	common/events.cpp \
	common/file.cpp \
	common/fs.cpp \
	common/gui_options.cpp \
	common/hashmap.cpp \
	common/language.cpp \
	common/localization.cpp \
	common/macresman.cpp \
	common/memory.cpp \
	common/memorypool.cpp \
	common/md5.cpp \
	common/mutex.cpp \
	common/osd_message_queue.cpp \
	common/path.cpp \
	common/platform.cpp \
	common/printman.cpp \
	common/punycode.cpp \
	common/random.cpp \
	common/rational.cpp \
	common/rendermode.cpp \
	common/rotationmode.cpp \
	common/str.cpp \
	common/stream.cpp \
	common/streamdebug.cpp \
	common/str-base.cpp \
	common/str-enc.cpp \
	common/encodings/singlebyte.cpp \
	common/system.cpp \
	common/textconsole.cpp \
	common/text-to-speech.cpp \
	common/tokenizer.cpp \
	common/translation.cpp \
	common/unicode-bidi.cpp \
	common/ustr.cpp \
	common/util.cpp \
	common/xpfloat.cpp \
	common/zip-set.cpp \
	common/std/std.cpp \
	common/compression/clickteam.cpp \
	common/compression/dcl.cpp \
	common/compression/gentee_installer.cpp \
	common/compression/gzio.cpp \
	common/compression/installshield_cab.cpp \
	common/compression/installshieldv3_archive.cpp \
	common/compression/packice.cpp \
	common/compression/powerpacker.cpp \
	common/compression/rnc_deco.cpp \
	common/compression/stuffit.cpp \
	common/compression/unarj.cpp \
	common/compression/unzip.cpp \
	common/compression/vise.cpp \
	common/formats/cue.cpp \
	common/formats/disk_image.cpp \
	common/formats/formatinfo.cpp \
	common/formats/iff_container.cpp \
	common/formats/ini-file.cpp \
	common/formats/json.cpp \
	common/formats/markdown.cpp \
	common/formats/po_parser.cpp \
	common/formats/prodos.cpp \
	common/formats/quicktime.cpp \
	common/formats/spectrum_tape.cpp \
	common/formats/winexe.cpp \
	common/formats/winexe_ne.cpp \
	common/formats/winexe_pe.cpp \
	common/formats/xmlparser.cpp \
	backends/platform/sdl/sdl.cpp \
	backends/platform/sdl/sdl-window.cpp \
	backends/fs/posix/posix-fs.cpp \
	backends/fs/posix/posix-fs-factory.cpp \
	backends/fs/posix/posix-iostream.cpp \
	engines/scumm/detection.cpp
